clc;
clear all;
close all;
f=20;
t=0:0.001:1;
x= sin(2*pi*f*t);
subplot(3,1,1);
plot(t,x);
title('original sinusoidal signal');
n=0.2*rand(size(t));
subplot(3,1,2);
plot(t,n);
title("noise signal");
ns=x+n;
subplot(3,1,3);
plot(t,ns);
title('noisy sinusoidal signal');
fns=fft(ns);
figure;
subplot(2,1,1);
plot(t,abs(fns));
title('mag of fourier transform');
xlabel('freq(hz)');
ylabel('mag');
subplot(2,1,2)
plot(t,angle(fns));
title('phase of transform');
xlabel('freq(hz)');
ylabel('phase(radians)');
subplot(3,1,3);
ifns=ifft(fns);
plot(t,ifns);
title('inverse fourier transform');